### ISSUE TITLE
Guardar variables entorno

### ISSUE THREAD

**Issue by JordiDevv** [JordiDevv/minishell#1]

**Comment by elsoriano** [comment]
char **ft_env_parser(char **envp) recibe las variables de entorno como parámetro, Lee el número de srings que contiene envp, crea un char ** donde asigna espacio con malloc para todos los strings que va copiando uno a uno utilizando la función ft_strdup de libft que guarda memoria para cada una de las strings copiada. Devuelve el puntero doble generado.
